### PR TITLE
Make floating panel for participants and transcript panel

### PR DESCRIPTION
**Pull request by ghost**
- [X] 🎉 Feature Enhancement
- [X] 🐛 Bug Fix

## Description
This pull request makes both the panels (participants & transcript) floatable.

Here is a clip:

https://user-images.githubusercontent.com/82395440/137479362-c2a09f4c-c3e1-4945-8f50-2abe183307cd.mp4

## Issue
This fixes issue #17 

Edit: Sorry if there are flashes. Moreover, as for the cursor, the cursors were not actually configured, but they will appear has a hand when the user hovers the floatable panels.

### CODE REVIEW

**Comment by Hyperion101010** [comment]
Thanks will check this today, there is one comment out block in code can you refactor it.

**Comment by AsianCat54x** [comment]
> Thanks will check this today, there is one comment out block in code can you refactor it.

Do you mean to remove that line?

**Comment by Hyperion101010** [comment]
Just update that comment.

**Comment by AsianCat54x** [comment]
> Ok looked at the code it works. @AsianCat54x you are on a roll!

Thanks :)

**Comment by sbalikondwar** [comment]
done added

**Pull request merged**
