### PR TITLE
Show notification on enter or leave

### LINKED ISSUE #37: [Feature]: Display notification whenever user joins or leaves the meeting
### Contact Details

asiancat75x@gmail.com

### Anything else?

Whenever the users join or leave the meeting, we should display messages so that they have a track of the users joining.

### PR DESCRIPTION
**Pull request by ghost**
## Type of Pull Request 

- [X] 🎉 Feature Enhancement

## Description
Display toast notifications whenever user enters or leaves the meeting

## Issue
Closes #37

### CODE REVIEW

**Comment by Akankshabhasin** [comment]
Hey @AsianCat54x , it looks great. 👍 
There is one check that is failing as tracked by SonarCloud.
Please check this link and try to resolve the bug  - [Link](https://sonarcloud.io/project/issues?id=symblai_symbl-twilio-video-react&pullRequest=38&resolved=false&types=BUG)

**Comment by AsianCat54x** [comment]
Oh okay!

**Comment by Hyperion101010** [comment]
Checked on my local pc works, great work @AsianCat54x  

We will send some goodies your way 🥇

**Comment by AsianCat54x** [comment]
I actually filled the form for swags :))))))))))

**Comment by Akankshabhasin** [comment]
Thanks a lot for contributing to Symbl.ai. 🙌 
We will be reaching out to the contributors for Developer Swags via email this week. 🎁

**Comment by ghost** [comment]
My pleasure :D

**Pull request merged**
